ALTER TABLE docentes
  DROP COLUMN IF EXISTS cedula_docente,
  DROP COLUMN IF EXISTS nombre1,
  DROP COLUMN IF EXISTS nombre2,
  DROP COLUMN IF EXISTS apellido1,
  DROP COLUMN IF EXISTS apellido2,
  DROP COLUMN IF EXISTS fecha_nac,
  DROP COLUMN IF EXISTS telefono,
  DROP COLUMN IF EXISTS correo;

ALTER TABLE estudiantes
  DROP COLUMN IF EXISTS cedula_escolar,
  DROP COLUMN IF EXISTS nombre1,
  DROP COLUMN IF EXISTS nombre2,
  DROP COLUMN IF EXISTS apellido1,
  DROP COLUMN IF EXISTS apellido2,
  DROP COLUMN IF EXISTS fecha_nac,
  DROP COLUMN IF EXISTS genero;

ALTER TABLE representantes
  DROP COLUMN IF EXISTS cedula_rep,
  DROP COLUMN IF EXISTS nombre1,
  DROP COLUMN IF EXISTS nombre2,
  DROP COLUMN IF EXISTS apellido1,
  DROP COLUMN IF EXISTS apellido2,
  DROP COLUMN IF EXISTS correo;

ALTER TABLE usuarios
  DROP COLUMN IF EXISTS correo;
